/* Generated by Yosys 0.58+84 (git sha1 f5c9e122d, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/alu4bit.v:1.1-35.10" *)
module alu4bit(clk, rst, A, B, sel, result);
  (* src = "../rtl/alu4bit.v:2.18-2.21" *)
  input clk;
  wire clk;
  (* src = "../rtl/alu4bit.v:3.18-3.21" *)
  input rst;
  wire rst;
  (* src = "../rtl/alu4bit.v:4.18-4.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "../rtl/alu4bit.v:5.18-5.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "../rtl/alu4bit.v:6.18-6.21" *)
  input [2:0] sel;
  wire [2:0] sel;
  (* src = "../rtl/alu4bit.v:7.22-7.28" *)
  output [3:0] result;
  reg [3:0] result;
  (* src = "../rtl/alu4bit.v:4.18-4.19" *)
  wire _000_;
  (* src = "../rtl/alu4bit.v:4.18-4.19" *)
  wire _001_;
  (* src = "../rtl/alu4bit.v:4.18-4.19" *)
  wire _002_;
  (* src = "../rtl/alu4bit.v:4.18-4.19" *)
  wire _003_;
  (* src = "../rtl/alu4bit.v:5.18-5.19" *)
  wire _004_;
  (* src = "../rtl/alu4bit.v:5.18-5.19" *)
  wire _005_;
  (* src = "../rtl/alu4bit.v:5.18-5.19" *)
  wire _006_;
  (* src = "../rtl/alu4bit.v:5.18-5.19" *)
  wire _007_;
  (* src = "../rtl/alu4bit.v:10.15-10.22" *)
  wire _008_;
  (* src = "../rtl/alu4bit.v:10.15-10.22" *)
  wire _009_;
  (* src = "../rtl/alu4bit.v:10.15-10.22" *)
  wire _010_;
  (* src = "../rtl/alu4bit.v:10.15-10.22" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  (* src = "../rtl/alu4bit.v:6.18-6.21" *)
  wire _121_;
  (* src = "../rtl/alu4bit.v:6.18-6.21" *)
  wire _122_;
  (* src = "../rtl/alu4bit.v:6.18-6.21" *)
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire [3:0] _131_;
  wire [1:0] _132_;
  wire [3:0] _133_;
  wire [1:0] _134_;
  wire [3:0] _135_;
  wire [1:0] _136_;
  wire [3:0] _137_;
  wire [1:0] _138_;
  wire [3:0] _139_;
  wire [1:0] _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:21.38-21.38|../rtl/alu4bit.v:14.9-24.16|/usr/local/bin/../share/yosys/techmap.v:579.28-579.29" *)
  wire [31:0] _149_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:21.38-21.38|../rtl/alu4bit.v:14.9-24.16|/usr/local/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [31:0] _150_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:21.38-21.38|../rtl/alu4bit.v:14.9-24.16|/usr/local/bin/../share/yosys/techmap.v:581.22-581.23" *)
  wire [7:0] _151_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:21.38-21.38|../rtl/alu4bit.v:14.9-24.16|/usr/local/bin/../share/yosys/techmap.v:586.19-586.22" *)
  wire [3:0] _152_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:17.31-17.36|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _153_;
  (* src = "../rtl/alu4bit.v:21.38-21.38|../rtl/alu4bit.v:14.9-24.16|/usr/local/bin/../share/yosys/techmap.v:605.13-605.15" *)
  wire _154_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [3:0] _155_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _156_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _157_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:292.26-292.70|/usr/local/bin/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "3" *)
  wire [3:0] _158_;
  (* src = "../rtl/alu4bit.v:17.31-17.36|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _159_;
  (* src = "../rtl/alu4bit.v:17.31-17.36|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _160_;
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _161_;
  (* src = "../rtl/alu4bit.v:18.31-18.36|/usr/local/bin/../share/yosys/techmap.v:293.27-293.63|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _162_;
  (* src = "../rtl/alu4bit.v:10.15-10.22" *)
  wire [3:0] alu_out;
  assign _039_ = ~_123_;
  assign _040_ = ~(_122_ & _121_);
  assign _041_ = _040_ | _039_;
  assign _042_ = _000_ & ~(_041_);
  assign _043_ = _121_ | ~(_122_);
  assign _044_ = _043_ | _039_;
  assign _045_ = _001_ & ~(_044_);
  assign _046_ = _045_ | _042_;
  assign _047_ = _004_ ^ _000_;
  assign _048_ = _122_ | _121_;
  assign _049_ = _123_ & ~(_048_);
  assign _050_ = _049_ & _047_;
  assign _051_ = _050_ | _046_;
  assign _052_ = _004_ | _000_;
  assign _053_ = _004_ & _000_;
  assign _054_ = _053_ | ~(_052_);
  assign _055_ = _039_ & ~(_040_);
  assign _056_ = _055_ & ~(_054_);
  assign _057_ = _039_ & ~(_043_);
  assign _058_ = _057_ & _047_;
  assign _059_ = _058_ | _056_;
  assign _060_ = _122_ | ~(_121_);
  assign _061_ = _039_ & ~(_060_);
  assign _062_ = _061_ & _052_;
  assign _063_ = _039_ & ~(_048_);
  assign _064_ = _063_ & _053_;
  assign _065_ = _064_ | _062_;
  assign _066_ = _065_ | _059_;
  assign _067_ = _066_ | _051_;
  assign _068_ = ~(_044_ & _041_);
  assign _069_ = _060_ | _039_;
  assign _070_ = _049_ | ~(_069_);
  assign _071_ = _070_ | _068_;
  assign _072_ = _057_ | _055_;
  assign _073_ = _063_ | _061_;
  assign _074_ = _073_ | _072_;
  assign _075_ = _074_ | _071_;
  assign _008_ = _075_ & _067_;
  assign _076_ = _041_ | ~(_001_);
  assign _077_ = _002_ & ~(_044_);
  assign _078_ = _076_ & ~(_077_);
  assign _079_ = _000_ & ~(_069_);
  assign _080_ = ~(_005_ ^ _001_);
  assign _081_ = _049_ & ~(_080_);
  assign _082_ = _081_ | _079_;
  assign _083_ = _078_ & ~(_082_);
  assign _084_ = ~(_005_ ^ _001_);
  assign _085_ = _004_ & ~(_000_);
  assign _086_ = _085_ ^ _084_;
  assign _087_ = _055_ & ~(_086_);
  assign _088_ = _080_ ^ _053_;
  assign _089_ = _057_ & ~(_088_);
  assign _090_ = _089_ | _087_;
  assign _091_ = ~(_005_ | _001_);
  assign _092_ = _061_ & ~(_091_);
  assign _093_ = ~(_005_ & _001_);
  assign _094_ = _063_ & ~(_093_);
  assign _095_ = _094_ | _092_;
  assign _096_ = _095_ | _090_;
  assign _097_ = _083_ & ~(_096_);
  assign _009_ = _075_ & ~(_097_);
  assign _098_ = _041_ | ~(_002_);
  assign _099_ = _003_ & ~(_044_);
  assign _100_ = _098_ & ~(_099_);
  assign _101_ = _001_ & ~(_069_);
  assign _102_ = _006_ ^ _002_;
  assign _103_ = _102_ & _049_;
  assign _104_ = _103_ | _101_;
  assign _105_ = _100_ & ~(_104_);
  assign _106_ = ~(_006_ | _002_);
  assign _107_ = ~(_006_ & _002_);
  assign _108_ = _106_ | ~(_107_);
  assign _109_ = _005_ | ~(_001_);
  assign _110_ = _084_ & ~(_085_);
  assign _111_ = _109_ & ~(_110_);
  assign _112_ = _111_ ^ _108_;
  assign _113_ = _055_ & ~(_112_);
  assign _114_ = _053_ & ~(_080_);
  assign _115_ = _093_ & ~(_114_);
  assign _116_ = _115_ ^ _102_;
  assign _117_ = _057_ & ~(_116_);
  assign _118_ = _117_ | _113_;
  assign _119_ = _061_ & ~(_106_);
  assign _120_ = _063_ & ~(_107_);
  assign _012_ = _120_ | _119_;
  assign _013_ = _012_ | _118_;
  assign _014_ = _105_ & ~(_013_);
  assign _010_ = _075_ & ~(_014_);
  assign _015_ = _041_ | ~(_003_);
  assign _016_ = _002_ & ~(_069_);
  assign _017_ = _007_ ^ _003_;
  assign _018_ = _017_ & _049_;
  assign _019_ = _018_ | _016_;
  assign _020_ = _015_ & ~(_019_);
  assign _021_ = ~(_007_ | _003_);
  assign _022_ = ~(_007_ & _003_);
  assign _023_ = _021_ | ~(_022_);
  assign _024_ = _006_ | ~(_002_);
  assign _025_ = _108_ & ~(_111_);
  assign _026_ = _024_ & ~(_025_);
  assign _027_ = _026_ ^ _023_;
  assign _028_ = _055_ & ~(_027_);
  assign _029_ = _102_ & ~(_115_);
  assign _030_ = _107_ & ~(_029_);
  assign _031_ = _030_ ^ _017_;
  assign _032_ = _057_ & ~(_031_);
  assign _033_ = _032_ | _028_;
  assign _034_ = _061_ & ~(_021_);
  assign _035_ = _063_ & ~(_022_);
  assign _036_ = _035_ | _034_;
  assign _037_ = _036_ | _033_;
  assign _038_ = _020_ & ~(_037_);
  assign _011_ = _075_ & ~(_038_);
  (* src = "../rtl/alu4bit.v:28.5-33.8" *)
  always @(posedge clk)
    if (rst) result[0] <= 1'h0;
    else result[0] <= alu_out[0];
  (* src = "../rtl/alu4bit.v:28.5-33.8" *)
  always @(posedge clk)
    if (rst) result[1] <= 1'h0;
    else result[1] <= alu_out[1];
  (* src = "../rtl/alu4bit.v:28.5-33.8" *)
  always @(posedge clk)
    if (rst) result[2] <= 1'h0;
    else result[2] <= alu_out[2];
  (* src = "../rtl/alu4bit.v:28.5-33.8" *)
  always @(posedge clk)
    if (rst) result[3] <= 1'h0;
    else result[3] <= alu_out[3];
  assign _131_[0] = _150_[3];
  assign _137_[1] = _150_[12];
  assign _149_[12:0] = { _149_[20], A[2:0], 2'h0, A[3:1], A };
  assign _150_[8:7] = 2'h0;
  assign _153_[0] = _149_[28];
  assign _121_ = sel[0];
  assign _122_ = sel[1];
  assign _123_ = sel[2];
  assign _000_ = A[0];
  assign _004_ = B[0];
  assign _001_ = A[1];
  assign _005_ = B[1];
  assign _002_ = A[2];
  assign _006_ = B[2];
  assign _003_ = A[3];
  assign _007_ = B[3];
  assign alu_out[0] = _008_;
  assign alu_out[1] = _009_;
  assign alu_out[2] = _010_;
  assign alu_out[3] = _011_;
endmodule
